### ISSUE TITLE
Not support 1.18.2?

### ISSUE THREAD

**Issue by qiuzilu** [spyeic/malilib-forge#1]
Hello,
Very happy I can find this mod because I'm in great need it!
But......
![QQ截图20230101112956](https://user-images.githubusercontent.com/64822124/210160244-540f880a-e925-4626-8a57-4ae8ebb6b95f.png)
The Minecraft version is 1.18.2 and forge is 40.1.92
Please solve this problem earlier.(挂印钞机2.5秒砍一刀用鼠标宏游戏必须处于焦点那我的电脑就只能干这一件事了啊啊啊啊啊)
And,Happy New Year!!!
https://corestudi0.github.io/newyear/

**Comment by qiuzilu** [comment]
[crash-2023-01-01_11.29.44-fml.txt](https://github.com/spyeic/malilib-forge/files/10328240/crash-2023-01-01_11.29.44-fml.txt)
[latest.log](https://github.com/spyeic/malilib-forge/files/10328241/latest.log)

**Comment by spyeic** [comment]
已修复
